# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  NAME: bup
  PATH: dist
  ARGS: "-ldflags='-s -w'"

env:
  CGO_ENABLED: 0

tasks:
  docs:
    desc: Zensical Docs
    cmd: |
      rm -rf .cache
      zensical serve --open

  pathmgr:
    desc: Download PathMgr
    cmd: |
      wget https://github.com/Bill-Stewart/PathMgr/releases/download/v2.0.0/PathMgr-2.0.0.zip
      unzip dist/pathmgr.zip -d dist/PathMgr

  prepare:
    desc: Prep Inno
    cmd: |
      task build:windows:386
      task build:windows:amd64
      mkdir -p dist/i386
      mkdir -p dist/x86_64
      cp -f dist/bup-windows-amd64.exe dist/i386/bup.exe
      cp -f dist/bup-windows-amd64.exe dist/x86_64/bup.exe

  inno:
    aliases: [setup]
    desc: Inno Setup
    cmd: iscc.exe installer.iss

  clean:
    desc: Clean
    cmd: rm -rf {{.PATH}}

  build:
    desc: Build All
    #deps: [clean]
    cmds:
      - for:
          matrix:
            OS: [darwin, linux, windows]
            ARCH: [amd64, arm64]
        cmd: |
          OUTPUT="{{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}"
          {{if eq .ITEM.OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
          echo "Building: ${OUTPUT}"
          GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"
        silent: false

      - cmd: echo "Finished Success"
        silent: false

  build:*:*:
    desc: Build OS:ARCH
    #deps: [clean]
    vars:
      OS: "{{index .MATCH 0}}"
      ARCH: "{{index .MATCH 1}}"
    requires:
      vars:
        - name: OS
          enum: [darwin, linux, windows]
        - name: ARCH
          enum: [amd64, arm64, "386"]
    cmd: |
      OUTPUT="{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      {{if eq .OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
      echo "Building: ${OUTPUT}"
      GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"

  build:*:
    desc: Build OS
    #deps: [clean]
    vars:
      OS: "{{index .MATCH 0}}"
      ARCH: "amd64"
    requires:
      vars:
        - name: OS
          enum: [darwin, linux, windows]
    cmd: |
      OUTPUT="{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      {{if eq .OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
      echo "Building: ${OUTPUT}"
      GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"
