# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  NAME: bup
  PATH: dist
  ARGS: -ldflags='-s -w'

env:
  CGO_ENABLED: 0

tasks:
  goup:
    cmd: |
      go get -u
      go mod tidy

  lint:
    desc: Lint
    cmd: |
      prettier --check .
      yamllint -c .github/yamllint.yaml .
      golangci-lint run
      actionlint

  clean:
    desc: Clean
    cmd: rm -rf {{.PATH}}

  build:
    desc: GoReleaser Build
    cmd: goreleaser build --snapshot --clean

  release:
    desc: GoReleaser Release
    cmd: goreleaser release --snapshot --clean

  docs:
    desc: Zensical Docs
    cmd: |
      rm -rf .cache
      zensical serve --open

  inno:
    aliases: [setup]
    desc: Inno Setup
    cmd: iscc.exe installer.iss

  pathmgr:
    desc: Download PathMgr
    cmd: |
      wget https://github.com/Bill-Stewart/PathMgr/releases/download/v2.0.0/PathMgr-2.0.0.zip -O dist/pathmgr.zip
      unzip dist/pathmgr.zip -d dist/PathMgr

  #build:
  #  desc: Build All
  #  #deps: [clean]
  #  cmds:
  #    - for:
  #        matrix:
  #          OS: [darwin, linux, windows]
  #          ARCH: [amd64, arm64]
  #      cmd: |
  #        OUTPUT="{{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}"
  #        {{if eq .ITEM.OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
  #        echo "Building: ${OUTPUT}"
  #        GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"
  #      silent: false
  #
  #    - cmd: echo "Finished Success"
  #      silent: false

  #build:*:*:
  #  desc: Build OS:ARCH
  #  vars:
  #    OS: "{{index .MATCH 0}}"
  #    ARCH: "{{index .MATCH 1}}"
  #  requires:
  #    vars:
  #      - name: OS
  #        enum: [darwin, linux, windows]
  #      - name: ARCH
  #        enum: [amd64, arm64, "386"]
  #  cmd: |
  #    OUTPUT="{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
  #    {{if eq .OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
  #    echo "Building: ${OUTPUT}"
  #    GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"

  #build:*:
  #  desc: Build OS
  #  #deps: [clean]
  #  vars:
  #    OS: "{{index .MATCH 0}}"
  #    ARCH: "amd64"
  #  requires:
  #    vars:
  #      - name: OS
  #        enum: [darwin, linux, windows]
  #  cmd: |
  #    OUTPUT="{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
  #    {{if eq .OS "windows"}}OUTPUT="${OUTPUT}.exe"{{end}}
  #    echo "Building: ${OUTPUT}"
  #    GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.ARGS}} -o "${OUTPUT}"
