# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  CGO_ENABLED: 0

tasks:
  goup:
    cmd: |
      go get -u
      go mod tidy

  lint:
    desc: Lint
    cmd: |
      prettier --check .
      yamllint -c .github/yamllint.yaml .
      golangci-lint run
      actionlint

  clean:
    desc: Clean All
    cmd: |
      rm -rf dist/client
      rm -rf out

  build:
    desc: GoReleaser Build
    cmd: goreleaser build --snapshot --clean

  release:
    desc: GoReleaser Release
    cmd: goreleaser release --snapshot --clean

  docs:
    desc: Zensical Docs
    cmd: |
      rm -rf .cache
      zensical serve --open

  inno:
    aliases: [setup]
    desc: Inno Setup
    cmd: iscc.exe installer.iss

  pathmgr:
    preconditions:
      - sh: test ! -d dist/PathMgr
        msg: "Already downloaded to: dist/PathMgr"
    desc: Download PathMgr
    cmd: |
      mkdir -p dist
      wget https://github.com/Bill-Stewart/PathMgr/releases/download/v2.0.0/PathMgr-2.0.0.zip -O dist/pathmgr.zip
      unzip dist/pathmgr.zip -d dist/PathMgr

  vhs:
    desc: Create VHS Tape
    summary: Requires a bup.yaml with a valid backup destination
    vars:
      TAPE_FILE: '{{.CLI_ARGS | default "demo.tape"}}'
    cmds:
      - task: vhs-pre
      - echo "Creating Tape - {{.TAPE_FILE}}"
      - cp -f "assets/{{.TAPE_FILE}}" "{{.TAPE_FILE}}"
      - vhs "{{.TAPE_FILE}}"
      - defer: rm -f "{{.TAPE_FILE}}"

  vhs-pre:
    desc: VHS Tape Cleanup
    cmd: rm -rf "$HOME/backup/bup"

  vhs-setup:
    desc: VHS Tape Cleanup
    cmd: |
      rm -rf "$HOME/backup/bup"
      mkdir -p "$HOME/backup"
      cat > bup.yaml << EOF
      clipboard: false
      destination: $HOME/backup
      excludes:
        - dist
        - out
        - '*.exe'
      EOF

  test:
    if: test ! -d dist/PathMgr
    #preconditions:
    #  - sh: test ! -d dist/PathMgr
    #    msg: "Already downloaded to: dist/PathMgr"
    desc: Test Command
    cmd: |
      echo "Taskfile.yaml test Successful (no test was run)..."
