# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  NAME: bup
  PATH: dist

tasks:
  clean:
    desc: Clean
    cmds:
      - cmd: rm -rf dist

  build:
    desc: Build All
    deps: [clean]
    cmds:
      - for:
          matrix:
            OS: [darwin, linux, windows]
            ARCH: [amd64, arm64]
        cmd: |
          {{if eq .ITEM.OS "windows"}}
          echo "Building: {{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}.exe"
          GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}.exe"
          {{else}}
          echo "Building: {{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}"
          GOOS={{.ITEM.OS}} GOARCH={{.ITEM.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}"
          {{end}}
        silent: false

      - cmd: echo "Finished Success"
        silent: false

  build:*:*:
    desc: Build OS:ARCH
    deps: [clean]
    vars:
      OS: "{{index .MATCH 0}}"
      ARCH: "{{index .MATCH 1}}"
    requires:
      vars:
        - name: OS
          enum: [darwin, linux, windows]
        - name: ARCH
          enum: [amd64, arm64]
    cmd: |
      {{if eq .OS "windows"}}
      echo "Building: {{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}.exe"
      #GOOS={{.OS}} GOARCH={{.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}.exe"
      {{else}}
      echo "Building: {{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      #GOOS={{.OS}} GOARCH={{.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      {{end}}

  build:*:
    desc: Build OS
    deps: [clean]
    vars:
      OS: "{{index .MATCH 0}}"
      ARCH: "amd64"
    requires:
      vars:
        - name: OS
          enum: [darwin, linux, windows]
    cmd: |
      {{if eq .OS "windows"}}
      echo "Building: {{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}.exe"
      #GOOS={{.OS}} GOARCH={{.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}.exe"
      {{else}}
      echo "Building: {{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      #GOOS={{.OS}} GOARCH={{.ARCH}} go build -o "{{.PATH}}/{{.NAME}}-{{.OS}}-{{.ARCH}}"
      {{end}}
