# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  CGO_ENABLED: 0

tasks:
  goup:
    aliases: [go, tidy]
    cmd: |
      go get -u
      go mod tidy

  lint:
    desc: Lint
    cmd: |
      prettier --check .
      yamllint -c .github/yamllint.yaml .
      golangci-lint run
      actionlint -shellcheck="-e SC2129"

  clean:
    desc: Clean All
    cmd: |
      rm -rf dist/client
      rm -rf out

  build:
    desc: GoReleaser Build
    cmd: goreleaser build --snapshot --clean

  release:
    desc: GoReleaser Release
    cmd: goreleaser release --snapshot --clean

  docs:
    desc: Zensical Docs
    cmd: |
      rm -rf .cache
      zensical serve --open

  inno:
    desc: Inno Setup
    aliases: [setup]
    deps: [pathmgr]
    cmd: iscc.exe installer.iss

  pathmgr:
    desc: Download PathMgr
    if: test ! -d dist/PathMgr
    cmd: |
      mkdir -p dist
      wget https://github.com/Bill-Stewart/PathMgr/releases/download/v2.0.0/PathMgr-2.0.0.zip -O dist/pathmgr.zip
      unzip dist/pathmgr.zip -d dist/PathMgr

  install:
    vars:
      TARGET_NAME: bup
    cmd: |
      go build
      mv {{.TARGET_NAME}} "${HOME}/bin/{{.TARGET_NAME}}"
      which {{.TARGET_NAME}}
      {{.TARGET_NAME}} -V

  vhs:*:
    desc: Create VHS Tape
    deps: [rm-backups, gen-config]
    vars:
      TAPE_FILE: '{{index .MATCH 0 | default "demo"}}'
    cmd: |
      echo "Creating Tape - assets/{{.TAPE_FILE}}.tape"
      vhs "assets/{{.TAPE_FILE}}.tape"

  rm-backups:
    desc: Remove bup backups
    cmd: |
      rm -rf "$HOME/backup/bup"

  gen-config:
    desc: Generate Config File
    if: test ! -f bup.yaml
    cmd: |
      rm -rf "$HOME/backup/bup"
      mkdir -p "$HOME/backup"
      cat > bup.yaml << EOF
      clipboard: false
      destination: $HOME/backup
      excludes:
        - dist
        - out
        - '*.exe'
      EOF

  build:*:*:
    desc: Build OS:ARCH
    vars:
      OS: "{{index .MATCH 0}}"
      ARCH: "{{index .MATCH 1}}"
    requires:
      vars:
        - name: OS
          enum: [darwin, linux, windows]
        - name: ARCH
          enum: [amd64, arm64, "386"]
    cmd: |
      echo "Building: {{.OS}} / {{.ARCH}}"
      GOOS={{.OS}} GOARCH={{.ARCH}} goreleaser build --snapshot --clean --single-target {{.CLI_ARGS}}
